# Waveshare TTGO 2.13 inch epaper display: Clock, calendar and current weather
# Weather icon help from https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/16

esphome:
  name: epaper213
  platform: ESP32
  board: esp32dev
  includes:
    - weather_icon_map.h

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      manual_ip:
        static_ip: 10.0.0.133
        gateway: 10.0.0.1
        subnet: 255.255.255.0
        dns1: 10.0.0.1
    - ssid: !secret work_wifi_ssid
      password: !secret work_wifi_password
  ap:
    ssid: "Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

logger:

ota:

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

time:
  - platform: sntp
    id: tm
    timezone: "Europe/Stockholm"
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - component.update: epaper
    on_time_sync:
      - then:
        #- component.update: epaper

font:
  - file: "gfonts://Roboto"
    id: roboto20
    size: 20
  - file: "gfonts://Roboto"
    id: roboto100
    size: 100
    glyphs: "0123456789:"
  - file: fonts/materialdesignicons-webfont.ttf
    id: mdi
    size: 20
    glyphs:
      - "\U000F00ED" # calendar
      - "\U000F0590" # weather-cloudy
      - "\U000F0F2F" # weather-cloudy-alert
      - "\U000F0E6E" # weather-cloudy-arrow-right
      - "\U000F0591" # weather-fog
      - "\U000F0592" # weather-hail
      - "\U000F0F30" # weather-hazy
      - "\U000F0898" # weather-hurricane
      - "\U000F0593" # weather-lightning
      - "\U000F067E" # weather-lightning-rainy
      - "\U000F0594" # weather-night
      - "\U000F0F31" # weather-night-partly-cloudy
      - "\U000F0595" # weather-partly-cloudy
      - "\U000F0F32" # weather-partly-lightning
      - "\U000F0F33" # weather-partly-rainy
      - "\U000F0F34" # weather-partly-snowy
      - "\U000F0F35" # weather-partly-snowy-rainy
      - "\U000F0596" # weather-pouring
      - "\U000F0597" # weather-rainy
      - "\U000F0598" # weather-snowy
      - "\U000F0F36" # weather-snowy-heavy
      - "\U000F067F" # weather-snowy-rainy
      - "\U000F0599" # weather-sunny
      - "\U000F0F37" # weather-sunny-alert
      - "\U000F14E4" # weather-sunny-off
      - "\U000F059A" # weather-sunset
      - "\U000F059B" # weather-sunset-down
      - "\U000F059C" # weather-sunset-up
      - "\U000F0F38" # weather-tornado
      - "\U000F059D" # weather-windy
      - "\U000F059E" # weather-windy-variant

display:
  - platform: waveshare_epaper
    dc_pin: GPIO17
    cs_pin: GPIO5
    busy_pin: GPIO4
    reset_pin: GPIO16
    rotation: 90°
    model: 2.13in-ttgo-dke  # -b74 also worked fine, but without partial update (-dke)
    update_interval: never
    full_update_every: 10
    id: epaper
    lambda: |-
      it.strftime(0, 2, id(roboto20), TextAlign::TOP_LEFT, "%a, %e %b", id(tm).now());
      if (id(weather).has_state()) {
        it.print(it.get_width(), 4, id(mdi), TextAlign::TOP_RIGHT, weather_icon_map[id(weather).state.c_str()].c_str());
      }
      if (id(temperature).has_state()) {
        it.printf(it.get_width()-25, 2, id(roboto20), TextAlign::TOP_RIGHT, "%.0f°C", id(temperature).state);
      }
      if (id(rainfall).has_state() && id(rainfall).state > 0) {
        it.printf(it.get_width()-70, 2, id(roboto20), TextAlign::TOP_RIGHT, "%.1fmm", id(rainfall).state);
      } else {
        it.print(it.get_width()-70, 2, id(roboto20), TextAlign::TOP_RIGHT, "     ");
      }
      //it.line(0, 25, it.get_width(), 25);
      it.strftime(it.get_width()/2, it.get_height(), id(roboto100), TextAlign::BOTTOM_CENTER, "%H:%M", id(tm).now());
      if (id(next_event).has_state()) {
        it.print(0, it.get_height()+2, id(mdi), TextAlign::BOTTOM_LEFT, "\U000F00ED");
        it.printf(20, it.get_height()+3, id(roboto20), TextAlign::BOTTOM_LEFT, "%s", id(next_event).state.c_str());
      }

sensor:
  - platform: mqtt_subscribe
    topic: epaper/wx/temp
    id: temperature
  - platform: mqtt_subscribe
    topic: epaper/wx/rain
    id: rainfall

text_sensor:
  - platform: mqtt_subscribe
    topic: epaper/wx/icon
    id: weather
  - platform: mqtt_subscribe
    id: next_event
    topic: epaper/nextevent

binary_sensor:
  - platform: gpio
    id: push_button
    pin: 
      number: GPIO39
      inverted: true
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - component.update: epaper
