# Lilygo T5 4.7 inch epaper display: Clock, calendar and current weather
# Weather icon help from https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/16

esphome:
  name: epaper47
  includes:
    - weather_icon_map.h

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.0.106
  ap:
    password: !secret fallback_password

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

logger:

ota:

time:
  - platform: sntp
    id: tm
    timezone: "Europe/Stockholm"
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - display.page.show: home
          - component.update: epaper
    on_time_sync:
      - then:
        - display.page.show: home
        - component.update: epaper  # TODO comment out once working

font:
  - file: "gfonts://Roboto"
    id: font_std
    size: 30
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|'’åöä"
  - file: "gfonts://Roboto@700"
    id: font_media_title
    size: 30
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|'’åöä"
  - file: "gfonts://Roboto"
    id: font_clock
    size: 150
    glyphs: "-0123456789:° "
  - file: fonts/FLIPclockblack.ttf
    id: flipclock
    size: 350
    glyphs: "0123456789:"
  - file: fonts/lcd.ttf
    id: lcd
    size: 350
    glyphs: "0123456789:"
  - file: "gfonts://Noto Sans Mono"
    id: font_symbol
    size: 30
    glyphs: "-.0123456789° ▲▼▁▂▃▄▅▆▇█▓"
  - file: fonts/materialdesignicons-webfont.ttf
    id: mdi_calendar
    size: 30
    glyphs:
      - "\U000F00ED" # calendar
  - file: fonts/materialdesignicons-webfont.ttf
    id: mdi_weather
    size: 150
    glyphs:
      - "\U000F0590" # weather-cloudy
      - "\U000F0F2F" # weather-cloudy-alert
      - "\U000F0E6E" # weather-cloudy-arrow-right
      - "\U000F0591" # weather-fog
      - "\U000F0592" # weather-hail
      - "\U000F0F30" # weather-hazy
      - "\U000F0898" # weather-hurricane
      - "\U000F0593" # weather-lightning
      - "\U000F067E" # weather-lightning-rainy
      - "\U000F0594" # weather-night
      - "\U000F0F31" # weather-night-partly-cloudy
      - "\U000F0595" # weather-partly-cloudy
      - "\U000F0F32" # weather-partly-lightning
      - "\U000F0F33" # weather-partly-rainy
      - "\U000F0F34" # weather-partly-snowy
      - "\U000F0F35" # weather-partly-snowy-rainy
      - "\U000F0596" # weather-pouring
      - "\U000F0597" # weather-rainy
      - "\U000F0598" # weather-snowy
      - "\U000F0F36" # weather-snowy-heavy
      - "\U000F067F" # weather-snowy-rainy
      - "\U000F0599" # weather-sunny
      - "\U000F0F37" # weather-sunny-alert
      - "\U000F14E4" # weather-sunny-off
      - "\U000F059A" # weather-sunset
      - "\U000F059B" # weather-sunset-down
      - "\U000F059C" # weather-sunset-up
      - "\U000F0F38" # weather-tornado
      - "\U000F059D" # weather-windy
      - "\U000F059E" # weather-windy-variant

external_components:
  - source: github://ashald/esphome@lilygo-t5-47  #github://guillempages/esphome@patch-2
    components:
      - lilygo_t5_47
  - source: github://pr#3255
    components:
      - display
      - online_image

online_image:
  - url: !secret album_art_url
    id: album_image

display:
  - platform: lilygo_t5_47
    rotation: 180°
    update_interval: 10s
    full_update_every: 60
    id: epaper
    pages:
      - id: standby
        lambda: |-
          #define xres 960
          #define yres 540
          it.strftime(xres/2, yres/2+25, id(lcd), TextAlign::CENTER, "%H:%M", id(tm).now());

      - id: home
        lambda: |-
          #define xres 960
          #define yres 540

          // Quadrants
          it.line(xres/2, 0, xres/2, yres);
          it.line(0, yres/2, xres, yres/2);


          // Date and time
          it.strftime(xres/4, yres/8, id(font_std), TextAlign::BOTTOM_CENTER, "%a, %e %b", id(tm).now());
          it.strftime(xres/4, yres/4, id(font_clock), TextAlign::CENTER, "%H:%M", id(tm).now());


          // Calendar
          #define xtime xres*7/12
          #define xname xres*8/12
          #define ylinespace 50

          it.print(xres*3/4, yres/8, id(mdi_calendar), TextAlign::BOTTOM_CENTER, "\U000F00ED");
          it.print(xres*3/4, yres/8, id(font_std), TextAlign::BOTTOM_CENTER, "Up next");

          int y = yres/4 - ylinespace;
          it.print(xtime, y, id(font_std), TextAlign::CENTER, "10:00");
          it.print(xname, y, id(font_std), TextAlign::CENTER_LEFT, "Stand-up");

          y += ylinespace;
          it.print(xtime, y, id(font_std), TextAlign::CENTER, "10:20");
          it.print(xname, y, id(font_std), TextAlign::CENTER_LEFT, "Planning");

          y += ylinespace;
          it.print(xtime, y, id(font_std), TextAlign::CENTER, "11:30");
          it.print(xname, y, id(font_std), TextAlign::CENTER_LEFT, "Dale / Manuel 1on1");


          // Weather
          #define xweather xres*1/8
          #define xtemp xres*3/8

          // Rain sparkline
          y = yres*5/8;
          if (id(rainsparkline).has_state() && strcmp(id(rainsparkline).state.c_str(), "▁▁▁▁▁▁▁▁")) {
            it.printf(xweather, y, id(font_symbol), TextAlign::BOTTOM_CENTER, "%s", id(rainsparkline).state.c_str());
          } else {
            it.print(xweather, y, id(font_symbol), TextAlign::BOTTOM_CENTER, "         ");
          }

          // Weather icon and current temperature
          y = yres*6/8;
          if (id(weather).has_state()) {
            it.print(xweather, y, id(mdi_weather), TextAlign::CENTER, weather_icon_map[id(weather).state.c_str()].c_str());
          } else {
            it.print(xweather, y, id(mdi_weather), TextAlign::CENTER, "\U000F0597");
          }
          if (id(temperature).has_state()) {
            it.printf(xtemp, y, id(font_clock), TextAlign::CENTER, "%.0f°", id(temperature).state);
          } else {
            it.print(xtemp, y, id(font_clock), TextAlign::CENTER, "-0°");
          }

          // Rainfall next hour, min/max temp
          y = yres*7/8;
          if (id(rainfall).has_state() && id(rainfall).state > 0) {
            it.printf(xweather, y, id(font_std), TextAlign::TOP_CENTER, "%.1f mm", id(rainfall).state);
          } else {
            it.print(xweather, y, id(font_std), TextAlign::TOP_CENTER, "        ");
          }
          if (id(tempmin).has_state() && id(tempmax).has_state()) {
            it.printf(xtemp, y, id(font_symbol), TextAlign::TOP_CENTER, "▲%.0f°▼%.0f°", id(tempmin).state, id(tempmax).state);
          }


          // Spotify
          #define xtitle xres*9/16
          #define ytitle yres*5/8
          #define xprogress xres*4/8
          #define yprogress yres*7/8
          #define progress_width xres/2

          if (id(media_state).has_state() && strcmp(id(media_state).state.c_str(), "playing") == 0) {
            it.image(xres-200, yres/2, id(album_image), COLOR_OFF, COLOR_ON);
            if (id(media_title).has_state() && id(media_artist).has_state()) {
              it.printf(xtitle, ytitle, id(font_media_title), TextAlign::BOTTOM_LEFT, "%s", id(media_title).state.c_str());
              it.printf(xtitle, ytitle, id(font_std), TextAlign::TOP_LEFT, "%s", id(media_artist).state.c_str());
            }

            // Progress bar
            if (id(media_duration).has_state() && id(media_start).has_state()) {
              int t_now = id(tm).now().timestamp;  // Unix time now
              int t_start = id(media_start).state + 1.6e9;  // Unix time that track started, bug in mqtt that loses precision on large numbers
              int t_elapsed = t_now - t_start;  // seconds into the track
              int t_remain = (t_elapsed - id(media_duration).state) * -1;
              //ESP_LOGD("progress_bar", "now %i, start %i, elapsed %i, remain %i", t_now, t_start, t_elapsed, t_remain);

              if (t_remain >= 0) {
                it.printf(xres/2, yprogress, id(font_std), TextAlign::TOP_LEFT, "%i:%02i", t_elapsed/60, t_elapsed%60);
                it.printf(xres, yprogress, id(font_std), TextAlign::TOP_RIGHT, "-%i:%02i", t_remain/60, t_remain%60);

                int progress_elapsed = progress_width * t_elapsed / id(media_duration).state;
                it.filled_rectangle(xres/2, yprogress-1, progress_width, 3);  // full-time bar
                it.filled_rectangle(xres/2, yprogress-3, progress_elapsed, 6);  // elapsed bad
                it.filled_circle(xprogress+progress_elapsed, yprogress, 8);
              }
            }
          } else {
            // TODO paused logo?
          }


sensor:
  - platform: mqtt_subscribe
    topic: epaper/wx/temp
    id: temperature
  - platform: mqtt_subscribe
    topic: epaper/wx/min
    id: tempmin
  - platform: mqtt_subscribe
    topic: epaper/wx/max
    id: tempmax
  - platform: mqtt_subscribe
    topic: epaper/wx/rain
    id: rainfall
  - platform: mqtt_subscribe
    topic: epaper/spotify/duration
    id: media_duration
  - platform: mqtt_subscribe
    topic: epaper/spotify/start
    id: media_start

text_sensor:
  - platform: mqtt_subscribe
    topic: epaper/wx/icon
    id: weather
  - platform: mqtt_subscribe
    topic: epaper/wx/rainsparkline
    id: rainsparkline
  - platform: mqtt_subscribe
    id: next_event
    topic: epaper/nextevent
  - platform: mqtt_subscribe
    topic: epaper/spotify/state
    id: media_state
  - platform: mqtt_subscribe
    topic: epaper/spotify/artist
    id: media_artist
  - platform: mqtt_subscribe
    topic: epaper/spotify/title
    id: media_title

binary_sensor:
  - platform: gpio
    id: push_button
    pin: 
      number: GPIO39
      inverted: true
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - component.update: epaper
