esphome:
  name: particulate
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT
  manual_ip:
    static_ip: 10.0.0.11
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    dns1: 10.0.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Particulate Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false  # Publish to MQTT, but not for Home Assistant (HA uses its own API)

web_server:

prometheus:

# For SDS011 particulate, 5V
uart:
  rx_pin: D3
  tx_pin: D4
  baud_rate: 9600

# For BH1750 lux sensor, 5V
i2c:
  sda: D2
  scl: D1
  scan: False

sensor:
  - platform: sds011
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 6min
  - platform: dht  # 3V3
    pin: D7
    temperature:
      name: "Particulate Temperature"
    humidity:
      name: "Particulate Humidity"
    update_interval: 60s
  - platform: bh1750
    name: "Outdoor Illuminance"
    id: illuminance
    measurement_duration: 69
    update_interval: 30s
    accuracy_decimals: 0
  - platform: template
    name: "Outdoor Illuminance Average"
    device_class: "illuminance"
    unit_of_measurement: "lx"
    icon: "mdi:brightness-auto"
    update_interval: 30s
    accuracy_decimals: 0
    lambda: |-
      return id(illuminance).state;
    filters:
      - sliding_window_moving_average:
          window_size: 20  # 10 min moving average
          send_every: 2
          send_first_at: 2

switch:
  - platform: restart
    name: "Particulate Restart"